### ISSUE TITLE
HC-LE Input layer legends missing a description 

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/local-effects#10]
For problem description see [here](https://github.com/clarity-h2020/data-package/issues/59#issuecomment-555108045) and a possible solution [here](https://github.com/clarity-h2020/data-package/issues/59#issuecomment-555398340).

**Comment by negroscuro** [comment]
Not sure about what is the issue here.
I added some kind of titles to every layer. This means each layer in our Geoserver has a name with underscore to technically use them, also a title to show with blanks (appropiate for a legend) and then a summary of its content.
