### ISSUE TITLE
Local effects - Scenario definition for Naples

### ISSUE THREAD

**Issue by luis-meteogrid** [clarity-h2020/local-effects#3]
We need the features that define the 3 events characterizing each future scenario for heat wave in Naples: temperature, length extent in days, and occurrence probability. Should you give us proposed names for each one, it would be great. I apologyze, I know you already sent us the definition I am asking for but I don't find it,

**Comment by RobAndGo** [comment]
Hi Luis,
I'm not sure if you have been getting links to this discussion concerning the naming of the scenarios and event, but I will post it here:
[https://github.com/clarity-h2020/local-effects/issues/2](https://github.com/clarity-h2020/local-effects/issues/2)
Regarding the names of how frequent the events are, it was decided to use:
**Frequent** - an event occurring on average once per year (probability = 1.0), 
**Occasional** - an event occurring on average once every 5 years (probability = 0.2), and 
**Rare** - an event occurring on average once every 20 years or longer (probability < 0.05)
@claudiahahn may add further to this....

**Comment by claudiahahn** [comment]
The events are defined in the following excel file. The last column comprises the temperature and duration for each event for Naples. 
[CLARITY_Base_Impact_Scenarios_Selection_v0.1.xlsx](https://github.com/clarity-h2020/local-effects/files/3107804/CLARITY_Base_Impact_Scenarios_Selection_v0.1.xlsx)

Let us know if anything is unclear.

**Comment by luis-meteogrid** [comment]
It seems to be rigth clear. We have already uploaded a complete set of local effects layers to GeoServer with the new name convention:

Local_Effects_LE_Tmrt_FrequentEvent_19710101-20001231_observations_3d_28C_Naples
Local_Effects_LE_Tmrt_FrequentEvent_historical_19710101-20001231_ensmean_3d_26C_Naples
Local_Effects_LE_Tmrt_FrequentEvent_rcp45_20110101-20401231_ensmean_3d_28C_Naples
Local_Effects_LE_Tmrt_FrequentEvent_rcp45_20410101-20701231_ensmean_3d_34C_Naples
Local_Effects_LE_Tmrt_FrequentEvent_rcp45_20710101-21001231_ensmean_3d_34C_Naples
Local_Effects_LE_Tmrt_FrequentEvent_rcp85_20110101-20401231_ensmean_3d_30C_Naples
Local_Effects_LE_Tmrt_FrequentEvent_rcp85_20410101-20701231_ensmean_3d_32C_Naples
Local_Effects_LE_Tmrt_FrequentEvent_rcp85_20710101-21001231_ensmean_3d_34C_Naples
Local_Effects_LE_Tmrt_OcasionalEvent_19710101-20001231_observations_3d_30C_Naples
Local_Effects_LE_Tmrt_OcasionalEvent_historical_19710101-20001231_ensmean_11d_30C_Naples
Local_Effects_LE_Tmrt_OcasionalEvent_rcp45_20110101-20401231_ensmean_13d_32C_Naples
Local_Effects_LE_Tmrt_OcasionalEvent_rcp45_20410101-20701231_ensmean_3d_38C_Naples
Local_Effects_LE_Tmrt_OcasionalEvent_rcp45_20710101-21001231_ensmean_11d_34C_Naples
Local_Effects_LE_Tmrt_OcasionalEvent_rcp85_20110101-20401231_ensmean_5d_34C_Naples
Local_Effects_LE_Tmrt_OcasionalEven_rcp85_20410101-20701231_ensmean_4d_38C_Naples
Local_Effects_LE_Tmrt_OcasionalEvent_rcp85_20710101-21001231_ensmean_4d_40C_Naples
Local_Effects_LE_Tmrt_RareEvent_19710101-20001231_observations_3d_32C_Naples
Local_Effects_LE_Tmrt_RareEvent_historical_19710101-20001231_ensmean_3d_36C_Naples
Local_Effects_LE_Tmrt_RareEvent_rcp45_20110101-20401231_ensmean_4d_40C_Naples
Local_Effects_LE_Tmrt_RareEvent_rcp45_20410101-20701231_ensmean_5d_40C_Naples
Local_Effects_LE_Tmrt_RareEvent_rcp45_20710101-21001231_ensmean_7d_40C_Naples
Local_Effects_LE_Tmrt_RareEvent_rcp85_20110101-20401231_ensmean_6d_38C_Naples
Local_Effects_LE_Tmrt_RareEvent_rcp85_20410101-20701231_ensmean_8d_40C_Naples
Local_Effects_LE_Tmrt_RareEvent_rcp85_20710101-21001231_ensmean_8d_40C_Naples

Should we have misunderstood  the convention please let us know.
