### ISSUE TITLE
Indentify UA Cities / Regions that Support LE Calculation

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/local-effects#4]
ATOS will check the list the cities (in urban atlas) for which we have all the layers to perform the local effects calculations, then generate a shapefile / GeoJson / ... with country code+ city name+ bounding box of the city.

We import this Shapfile as Taxonomy, similar to the countries Taxonomy in CSIS Drupal. When the user has selected a country, we filter the list of cities by country code. In addition to the study area field (geometry), we add a new field (e.g. 'city') to the Study Entity Type.

See also https://github.com/clarity-h2020/map-component/issues/24

**Comment by p-a-s-c-a-l** [comment]
@therter The respective layer is available and used in CSIS, right? 
So we can close this issue?

**Comment by therter** [comment]
> The respective layer is available and used in CSIS, right?
> So we can close this issue?

That is right
