### ISSUE TITLE
Percentage layers for outdoor Heat Wave

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/local-effects#6]
@alecapolupo In order to determine radiant Temperature (Tmrt), it is needed to estimate superficial temperatures (Ts) for each type of surface. This depends on insolation and ventilation. Taking this into account we need to know if buildings are placed in areas with high/medium/low urban density. 

@negroscuro told us that his approach will be to substract the area occupied by these buildings from urban density areas so as to avoid getting overlaps among the different areas. We think that it could be more useful to preserve the original areas so we could determine the percentage of buildings that there are in each urban density area.

This would make sense to you? If you'd rather have the layers with a substraction we'll have to modify the script to account for this.

**Comment by inakiMTG** [comment]
Continuing with the discussion, we need to know how to process the gaps inside a cell. That is, if in a cell there is a zone not associated to any of the layers, how should we process it?  

One possible solution is to calculate its temperature by weighting the occupied area without taking the gap into account. Another solution may be to associate a temperature to non-deifnid areas. For example, the air temperature. 

What do you think? @alecapolupo

**Comment by ghost** [comment]
Hi @ghilbrae,

layers 9, 10, 11, 12 are related to the urban fabric (9=high dense, 10= medium, 11= Industrial, commercial, public, military and private units). Moreover, @negroscuro intersect buildings and the urban fabric to assign the most of parameters. So, you can ask him to have the intersection outcome.

**Comment by ghost** [comment]
Hi @inakiMTG,

I think that the first solution is the best to adopt ( calculate its temperature by weighting the occupied area without taking the gap into account).

**Comment by luis-meteogrid** [comment]
Thanks @alecapolupo that is what we have implemented into the algorithm

**Comment by p-a-s-c-a-l** [comment]
> Thanks @alecapolupo that is what we have implemented into the algorithm

So we can close this issue?
